/* @macrome
 * @generatefailed
 * @generatedby /node_modules/@macrome/generator-typescript/lib/index.js
 * @generatedfrom ./api-factory.ts#1640623852812
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
throw new Error(`SyntaxError: /Users/conartist6/dev/repos/iter-tools-regex/lib/async/api-factory.ts: Support for the experimental syntax 'jsx' isn't currently enabled (5:27):

  3 | import { Pattern, PatternLike } from '../types';
  4 |
> 5 | export const apiFactory = <I>(
    |                           ^
  6 |   generate: (pattern: Pattern, iterable: I) => AsyncIterableIterator<Array<string | null>>,
  7 | ) => {
  8 |   const exec = async (pattern: string | PatternLike, iterable: I) => {

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
    at Parser._raise (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:476:17)
    at Parser.raiseWithData (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:469:17)
    at Parser.expectOnePlugin (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:3820:18)
    at Parser.parseExprAtom (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:12577:18)
    at Parser.parseExprSubscripts (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:12149:23)
    at Parser.parseUpdate (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:12129:21)
    at Parser.parseMaybeUnary (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:12104:23)
    at Parser.parseMaybeUnaryOrPrivate (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:11901:61)
    at Parser.parseExprOps (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:11908:23)
    at Parser.parseMaybeConditional (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:11878:23)`);