/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./api.ts#1646671178903
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { parse } from '../pattern';

const _ = Symbol.for('_');

export class AsyncApi {
  constructor(generate) {
    this[_] = { generate };
  }

  exec = async (pattern, iterable) => {
    const { generate } = this[_];
    const step = await generate(parse(pattern), iterable).next();

    return step.done ? null : step.value;
  };

  test = async (pattern, iterable) => {
    const { exec } = this;
    return (await exec(pattern, iterable)) !== null;
  };

  execGlobal = (pattern, iterable) => {
    const { generate } = this[_];
    const pattern_ = parse(pattern);
    return {
      [Symbol.asyncIterator]() {
        return generate(pattern_, iterable);
      },
    };
  };
}
