/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./api.ts#1648067002710
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

(exports.AsyncApi = void 0);
var _pattern = require("../pattern");

const _ = Symbol.for('_');

class AsyncApi {
  constructor(generate) {
    this[_] = { generate };
  }

  exec = async (pattern, iterable) => {
    const { generate } = this[_];
    const step = await generate((0, _pattern.parse)(pattern), iterable).next();

    return step.done ? [] : step.value;
  };

  test = async (pattern, iterable) => {
    const { exec } = this;
    return (await exec(pattern, iterable)).length > 0;
  };

  execGlobal = (pattern, iterable) => {
    const { generate } = this[_];
    const pattern_ = (0, _pattern.parse)(pattern);
    return {
      [Symbol.asyncIterator]() {
        return generate(pattern_, iterable);
      },
    };
  };
}

exports.AsyncApi = AsyncApi;
