/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./chunked.ts#1647109390475
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

Object.defineProperty(exports, "Pattern", {
  enumerable: true,

  get: function() {
    return _pattern.Pattern;
  }
});

(exports.execGlobal = (exports.exec = void 0));

Object.defineProperty(exports, "parse", {
  enumerable: true,

  get: function() {
    return _pattern.parse;
  }
});

(exports.test = void 0);
var _asyncPeekerate = _interopRequireDefault(require("iter-tools-es/methods/async-peekerate"));
var _peekerate = _interopRequireDefault(require("iter-tools-es/methods/peekerate"));
var _api = require("./api");
var _engine = require("../internal/engine");
var _utils = require("./internal/utils");

var _pattern = require("../pattern");

function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : {
    default: obj
  };
}

const { exec, test, execGlobal } = new _api.AsyncApi(async function* generate(
  pattern,
  iterable,
) {
  const engine = new _engine.Engine(pattern);
  let chunkPeekr = await (0, _asyncPeekerate.default)((0, _utils.map)(iterable, _peekerate.default));
  let idx = 0;
  let value, done;

  const empty = chunkPeekr.done || chunkPeekr.value.done;

  try {
    ({ value, done } = engine.step0(true, empty, idx, chunkPeekr.value && chunkPeekr.value.value));
    if (value !== null) yield* value;

    if (empty) return;

    let peekr = chunkPeekr.value;
    try {
      while (!done && !peekr.done) {
        engine.step1(peekr.value);

        peekr = peekr.advance();

        if (peekr.done) {
          chunkPeekr = await chunkPeekr.advance();
          if (chunkPeekr.done) {
            // there may be a final empty chunk
            // and we want a single check for doneness
            // so always simulate a final empty chunk
            peekr = (0, _peekerate.default)([]);
          } else {
            peekr = chunkPeekr.value;
          }
        }

        ({ value, done } = engine.step0(false, peekr.done, idx, peekr.value));
        if (value !== null) yield* value;
        idx++;
      }
    } finally {
      peekr.return();
    }
  } finally {
    await chunkPeekr.return();
  }
});

exports.execGlobal = execGlobal;
exports.test = test;
exports.exec = exec;
