/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./index.ts#1640623852812
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export type { parse } from '../regex';
export declare const {
  exec,
  test,
  execGlobal
};