/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./index.ts#1649095331573
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

Object.defineProperty(exports, "Pattern", {
  enumerable: true,

  get: function() {
    return _pattern.Pattern;
  }
});

(exports.execGlobal = (exports.exec = void 0));

Object.defineProperty(exports, "parse", {
  enumerable: true,

  get: function() {
    return _pattern.parse;
  }
});

(exports.test = void 0);
var _asyncPeekerate = _interopRequireDefault(require("iter-tools-es/methods/async-peekerate"));
var _api = require("./api");
var _engine = require("../internal/engine");

var _pattern = require("../pattern");

function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : {
    default: obj
  };
}

const { exec, test, execGlobal } = new _api.AsyncApi(async function* generate(
  pattern,
  iterable,
) {
  const peekr = await (0, _asyncPeekerate.default)(iterable);
  const engine = new _engine.Engine(pattern);
  let value;
  let done = false;
  let lastChr = null;
  let chr = peekr.done ? null : peekr.value;

  try {
    ({ value, done } = engine.step0(lastChr, chr));
    if (value !== null) yield* value;

    while (!done && chr !== null) {
      engine.step1(chr);

      await peekr.advance();
      lastChr = chr;
      chr = peekr.done ? null : peekr.value;

      ({ value, done } = engine.step0(lastChr, chr));
      if (value !== null) yield* value;
    }
  } finally {
    await peekr.return();
  }
});

exports.execGlobal = execGlobal;
exports.test = test;
exports.exec = exec;
