/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./index.ts#1646521200932
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export type { parse, Pattern } from '../pattern';

export declare const { exec, test, execGlobal };
