/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./utils.ts#1640623852812
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export async function* map(iterable, mapper) {
  for await (const value of iterable) {
    yield await mapper(value);
  }
}