/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./api-factory.ts#1646457865061
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { parse } from './regex';

const { hasOwnProperty } = Object.prototype;

const bindAll = obj => {
  for (const key in obj) {
    if (hasOwnProperty.call(obj, key)) {
      const fn = obj[key];
      if (typeof fn === 'function') {
        obj[key] = fn.bind(obj);
      }
    }
  }
  return obj;
};

export const apiFactory = (generate) => {
  return bindAll({
    exec(pattern, iterable) {
      const step = generate(parse(pattern), iterable).next();

      return step.done ? null : step.value;
    },
    test(pattern, iterable) {
      return this.exec(pattern, iterable) !== null;
    },
    execGlobal(pattern, iterable) {
      return generate(parse(pattern), iterable);
    },
  });
};
