/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./api-factory.ts#1645379747809
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Pattern, PatternLike } from './types';
export declare const apiFactory;