/* @macrome
 * @generatedby /node_modules/@macrome/generator-typescript/lib/index.js
 * @generatedfrom ./api-factory.ts#1640623852812
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { parse } from './regex';
export const apiFactory = generate => {
  const exec = (pattern, iterable) => {
    const step = generate(parse(pattern), iterable).next();
    return step.done ? null : step.value;
  };

  const test = (pattern, iterable) => {
    return exec(pattern, iterable) !== null;
  };

  const execGlobal = (pattern, iterable) => {
    return generate(parse(pattern), iterable);
  };

  return {
    exec,
    test,
    execGlobal
  };
};