/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./api-factory.ts#1646457865061
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Pattern, PatternLike } from './types';

interface Api<I> {
  exec(pattern: string | PatternLike, iterable: I): null | Array<string | null>;
  test(pattern: string | PatternLike, iterable: I): boolean;
  execGlobal(pattern: string | PatternLike, iterable: I): Iterable<Array<string | null>>;
}

type Generate<I> = (pattern: Pattern, iterable: I) => IterableIterator<Array<string | null>>;

export declare const apiFactory: <I>(generate: Generate<I>) => Api<I>;
