/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./api.ts#1648067012913
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

(exports.Api = void 0);

var _pattern = require("./pattern");

const _ = Symbol.for('_');

class Api {
  constructor(generate) {
    this[_] = { generate };
  }

  exec = (pattern, iterable) => {
    const { generate } = this[_];
    const step = generate((0, _pattern.parse)(pattern), iterable).next();

    return step.done ? [] : step.value;
  };

  test = (pattern, iterable) => {
    const { exec } = this;
    return exec(pattern, iterable).length > 0;
  };

  execGlobal = (pattern, iterable) => {
    const { generate } = this[_];
    const pattern_ = (0, _pattern.parse)(pattern);
    return {
      [Symbol.iterator]() {
        return generate(pattern_, iterable);
      },
    };
  };
}

exports.Api = Api;
