/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./captures.ts#1646373107609
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Capture } from './types';

export declare function flattenCapture(capture: Capture, capturesLen: number): Array<string | null>;
