/* @macrome
 * @generatefailed
 * @generatedby /node_modules/@macrome/generator-typescript/lib/index.js
 * @generatedfrom ./captures.ts#1640623852812
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
throw new Error(`SyntaxError: /Users/conartist6/dev/repos/iter-tools-regex/lib/captures.ts: Unexpected token, expected "," (3:32)

  1 | import { Capture } from './types';
  2 |
> 3 | function _flattenCapture(capture: Capture, captures: Array<string | null>) {
    |                                 ^
  4 |   const { result, children, idx } = capture;
  5 |   captures[idx] = result;
  6 |   if (result !== null) {
    at Parser._raise (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:476:17)
    at Parser.raiseWithData (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:469:17)
    at Parser.raise (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:430:17)
    at Parser.unexpected (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:3789:16)
    at Parser.expect (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:3773:28)
    at Parser.parseBindingList (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:11502:14)
    at Parser.parseFunctionParams (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14904:24)
    at Parser.parseFunction (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14882:10)
    at Parser.parseFunctionStatement (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14495:17)
    at Parser.parseStatementContent (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14157:21)`);