/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./index.ts#1649621194483
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

Object.defineProperty(exports, "Pattern", {
  enumerable: true,

  get: function() {
    return _pattern.Pattern;
  }
});

(exports.execGlobal = (exports.exec = void 0));

Object.defineProperty(exports, "parse", {
  enumerable: true,

  get: function() {
    return _pattern.parse;
  }
});

(exports.test = void 0);
var _peekerate = _interopRequireDefault(require("iter-tools-es/methods/peekerate"));
var _api = require("./api");
var _engine = require("./internal/engine");

var _pattern = require("./pattern");

function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : {
    default: obj
  };
}

const { exec, test, execGlobal } = new _api.Api(function* generate(
  pattern,
  iterable,
) {
  const peekr = (0, _peekerate.default)(iterable);
  const engine = new _engine.Engine(pattern);

  try {
    engine.feed(null);

    while (!engine.done && !peekr.done) {
      if (engine.starved) {
        engine.feed(peekr.value);
        peekr.advance();
      }
      yield* engine.step0();
      engine.step1();
    }

    engine.feed(null);

    yield* engine.step0();
  } finally {
    peekr.return();
  }
});

exports.execGlobal = execGlobal;
exports.test = test;
exports.exec = exec;
