/* @macrome
 * @generatefailed
 * @generatedby /node_modules/@macrome/generator-typescript/lib/index.js
 * @generatedfrom ./literals.ts#1640623852813
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
throw new Error(`SyntaxError: /Users/conartist6/dev/repos/iter-tools-regex/lib/literals.ts: Unexpected token, expected "," (4:24)

  2 | import { Flags } from './types';
  3 |
> 4 | export const code = (str: string) => str.charCodeAt(0);
    |                         ^
  5 | const upperValue = (c: number) => String.fromCharCode(c).toUpperCase().charCodeAt(0);
  6 | const inRange = (value: number, lo: number, hi: number) => value >= lo && value <= hi;
  7 |
    at Parser._raise (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:476:17)
    at Parser.raiseWithData (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:469:17)
    at Parser.raise (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:430:17)
    at Parser.unexpected (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:3789:16)
    at Parser.expect (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:3773:28)
    at Parser.parseParenAndDistinguishExpression (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:12883:14)
    at Parser.parseExprAtom (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:12476:23)
    at Parser.parseExprSubscripts (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:12149:23)
    at Parser.parseUpdate (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:12129:21)
    at Parser.parseMaybeUnary (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:12104:23)`);