/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./literals.ts#1646373107610
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Character, CharacterClass, CharacterClassRange, CharacterSet, Node } from 'regexpp/ast';
import { Flags } from './types';

export declare const code;

export type Tester = (c: number) => boolean;

// These definitions are mostly taken from MDN
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes

export declare const testNotNewline: Tester;
export declare const testDigit: Tester;
export declare const testSpace: Tester;
export declare const testWord: Tester;
export declare const testAny: Tester;

// Because this is unimplemented
export declare const testProperty: Tester;

export declare const getCharTester;

export declare const getCharSetTester;

export declare const getCharClassRangeTester;

export declare const getCharClassTester;

export declare const getTester;
