/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./pattern.ts#1648561535139
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import type { Flags, PatternLike } from './types';

declare const _: unique symbol;

export declare const getPatternInternal: (pattern: Pattern) => unknown;

export declare class Pattern implements Flags {
  private readonly [_];

  readonly source: string;
  readonly flags: string;
  readonly global: boolean;
  readonly ignoreCase: boolean;
  readonly multiline: boolean;
  readonly dotAll: boolean;
  readonly unicode: boolean;
  readonly sticky: boolean;

  constructor(pattern: PatternLike | string, flags?: string | undefined);
}

export declare const parse: (pattern: PatternLike | string, flags?: string | undefined) => Pattern;
