/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./pattern.ts#1646521429693
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { buildPatternInternal } from './internal/regex';
import { Parser } from './internal/ast';

const _ = Symbol.for('_');

export const getPatternInternal = (pattern) => {
  return pattern[_];
};

export class Pattern {
  constructor(pattern, flags) {
    let source;
    let _flags;

    if (pattern instanceof Pattern) {
      return pattern;
    } else if (typeof pattern === 'string') {
      source = pattern;
      _flags = flags || '';
    } else {
      ({ source } = pattern);
      _flags = flags !== undefined ? flags : pattern.flags || '';
    }

    const parser = new Parser();
    parser.parseFlags(_flags); // for validation
    const ast = parser.parsePattern(source);

    const flagsObj = {
      global: _flags.includes('g'),
      ignoreCase: _flags.includes('i'),
      multiline: _flags.includes('m'),
      dotAll: _flags.includes('s'),
      unicode: _flags.includes('u'),
    };

    this[_] = buildPatternInternal(ast, flagsObj);
    this.source = source;
    this.flags = _flags;
    Object.assign(this, flagsObj);
  }
}

export const parse = (pattern, flags) => {
  return new Pattern(pattern, flags);
};
