/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./pattern.ts#1646373107611
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { MatchState, Width0Matcher } from './types';

export declare class Pattern {
  readonly source: string;
  readonly flags: string;
  readonly global: boolean;
  readonly ignoreCase: boolean;
  readonly multiline: boolean;
  readonly dotAll: boolean;
  readonly unicode: boolean;
  readonly matcher: Width0Matcher;
  readonly initialState: MatchState;
}

export declare const asPattern;
