/* @macrome
 * @generatedby /node_modules/@macrome/generator-typescript/lib/index.js
 * @generatedfrom ./pattern.ts#1640623852813
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export class Pattern {}
export const asPattern = pattern => {
  return Object.assign(Object.create(Pattern.prototype), pattern);
};