/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./pattern.ts#1646373107611
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export class Pattern {}

export const asPattern = pattern => {
  return Object.assign(Object.create(Pattern.prototype), pattern);
};
