/* @macrome
 * @generatedby /node_modules/@macrome/generator-typescript/lib/index.js
 * @generatedfrom ./rbt.ts#1640623852813
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
// @ts-ignore
import _createTree from 'functional-red-black-tree';
export const createTree = _createTree;