/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./regex.ts#1646373107613
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import type { Width0Matcher, Flags, RepetitionState, PatternLike } from './types';
import { Pattern } from './pattern';

type ParserState = {
  flags: Flags;
  qIdxs: Array<number>;
  qIdx: number;
  cIdx: number;
  initialRepetitionStates: Array<RepetitionState>;
};

export declare const parse;
