/* @macrome
 * @generatefailed
 * @generatedby /node_modules/@macrome/generator-typescript/lib/index.js
 * @generatedfrom ./regex.ts#1640623852813
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
throw new Error(`SyntaxError: /Users/conartist6/dev/repos/iter-tools-regex/lib/regex.ts: Unexpected token, expected "from" (2:12)

  1 | import emptyStack from '@iter-tools/imm-stack';
> 2 | import type {
    |             ^
  3 |   Matcher,
  4 |   Result,
  5 |   MatchState,
    at Parser._raise (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:476:17)
    at Parser.raiseWithData (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:469:17)
    at Parser.raise (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:430:17)
    at Parser.unexpected (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:3789:16)
    at Parser.expectContextual (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:3744:18)
    at Parser.parseImport (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:15704:12)
    at Parser.parseStatementContent (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14223:27)
    at Parser.parseStatement (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14113:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14739:25)
    at Parser.parseBlockBody (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14730:10)`);