/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./types.ts#1646459986349
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export {};
