/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./types.ts#1645379759898
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { ImmutableStackFrame as Stack } from '@iter-tools/imm-stack';
export { Stack };