/* @macrome
 * @generatefailed
 * @generatedby /node_modules/@macrome/generator-typescript/lib/index.js
 * @generatedfrom ./types.ts#1640623852813
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
throw new Error(`SyntaxError: /Users/conartist6/dev/repos/iter-tools-regex/lib/types.ts: Support for the experimental syntax 'flow' isn't currently enabled (4:8):

  2 | import { ImmutableTree } from './rbt';
  3 |
> 4 | export type { Pattern } from './pattern';
    |        ^
  5 |
  6 | export { Stack };
  7 |

Add @babel/preset-flow (https://git.io/JfeDn) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://git.io/vb4yb) to the 'plugins' section to enable parsing.
    at Parser._raise (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:476:17)
    at Parser.raiseWithData (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:469:17)
    at Parser.expectOnePlugin (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:3820:18)
    at Parser.isExportDefaultSpecifier (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:15490:16)
    at Parser.maybeParseExportDefaultSpecifier (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:15366:14)
    at Parser.parseExport (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:15319:29)
    at Parser.parseStatementContent (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14229:27)
    at Parser.parseStatement (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14113:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14739:25)
    at Parser.parseBlockBody (/Users/conartist6/dev/repos/iter-tools-regex/node_modules/@macrome/generator-typescript/node_modules/@babel/parser/lib/index.js:14730:10)`);