/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./utils.ts#1646373107614
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export declare function map<V, M>(iterable: Iterable<V>, mapper: (v: V) => M): Iterable<M>;
