/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./captures.ts#1653314072950
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

(exports.flattenCapture = flattenCapture);

function _flattenCapture(capture, captures) {
  const { result, children, idx } = capture;
  captures[idx] = result;
  if (result !== null) {
    for (const subCapture of children) {
      _flattenCapture(subCapture, captures);
    }
  }
}

function flattenCapture(capture, capturesLen) {
  const captures = new Array(capturesLen).fill(undefined);
  _flattenCapture(capture, captures);
  return captures;
}
