/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./debug.ts#1653315392843
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

(exports.debugPrint = void 0);

const debugPrint = matcher => {
  if (matcher === null) return null;

  let m = matcher;
  let str = '';
  while (m !== null) {
    const { props } = m;

    if (typeof matcher.match !== 'function') {
      throw new Error('debugPrint can only print matchers.');
    }

    switch (m.name) {
      case 'literal':
        str += props.value;
        break;
      case 'boundaryAssertion':
        str += '\\b';
        break;
      case 'edgeAssertion':
        str += props.kind === 'start' ? '^' : '$';
        break;
      case 'repeat':
        if (props.repeatCont.name !== 'unmatched') {
          str += `(${props.exprCont.seqs.map((m) => debugPrint(m)).join('|')})*`;
        }
        break;
      case 'expression':
        str += `(${props.matchers.map((m) => debugPrint(m)).join('|')})`;
        // next is already distributed into matchers
        return str;
      default:
        break;
    }
    m = m.next;
  }
  return str;
};

exports.debugPrint = debugPrint;
