/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./rbt.ts#1647109390481
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

(exports.createTree = void 0);
var _functionalRedBlackTree = _interopRequireDefault(require("functional-red-black-tree"));

function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : {
    default: obj
  };
}

const createTree =
  _functionalRedBlackTree.default;

exports.createTree = createTree;
