/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./types.ts#1653274711573
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

(exports.successType = (exports.exprType = (exports.contType = void 0)));
const contType = Symbol('continuation');
exports.contType = contType;
const exprType = Symbol('expr');
exports.exprType = exprType;
const successType = Symbol('success');
exports.successType = successType;
