/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./types.ts#1647109390482
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

Object.defineProperty(exports, "Stack", {
  enumerable: true,

  get: function() {
    return _immStack.ImmutableStackFrame;
  }
});

var _immStack = require("@iter-tools/imm-stack");
