/* @macrome
 * @generatedby @macrome/generator-typescript
 * @generatedfrom ./utils.ts#1647109390483
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});

(exports.map = map);

function* map(iterable, mapper) {
  for (const value of iterable) {
    yield mapper(value);
  }
}
